version: "2"
networks:
    network:

services:
    ca_dopmam:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-dopmam
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=7054
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - ../ca-config/dopmam.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
            - ../organizations/fabric-ca/dopmam:/etc/hyperledger/fabric-ca-server
        container_name: ca_dopmam
        networks:
            - network

    ca_shifa:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-shifa
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=8054
        ports:
            - "8054:8054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - ../ca-config/shifa.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
            - ../organizations/fabric-ca/shifa:/etc/hyperledger/fabric-ca-server
        container_name: ca_shifa
        networks:
            - network

    ca_naser:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-naser
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=9054
        ports:
            - "9054:9054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - ../ca-config/naser.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
            - ../organizations/fabric-ca/naser:/etc/hyperledger/fabric-ca-server
        container_name: ca_naser
        networks:
            - network

    ca_orderer:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-orderer
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_PORT=10054
        ports:
            - "10054:10054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - ../ca-config/orderer.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
            - ../organizations/fabric-ca/orderer:/etc/hyperledger/fabric-ca-server
        container_name: ca_orderer
        networks:
            - network
